included:
  - LocalEventsExplorer/
  - LocalEventsExplorerTests/

excluded:
  - LocalEventsExplorerUITests

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicit_return
  - sorted_imports

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 250
  error: 400

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 50
  error: 80

identifier_name:
  min_length: 2
  excluded:
    - id
    - to
    - x
    - y
